using egregore.Generators;
using egregore.Ontology;
using Xunit;
using Xunit.Abstractions;

namespace egregore.Tests.Generators
{
    public class GeneratorTests
    {
        private readonly ITestOutputHelper _output;

        public GeneratorTests(ITestOutputHelper output)
        {
            _output = output;
        }

        [Fact]
        public void Can_generate_models_from_schema()
        {
            var schema = new Schema { Name = "Customer" };
            schema.Properties.Add(new SchemaProperty { Name = "Name", Type = "string" });
            
            var sb = new IndentAwareStringBuilder();
            var generator = new ModelGenerator();
            generator.Generate(sb, new Namespace(Constants.DefaultNamespace), 1, schema);
            sb.InsertAutoGeneratedHeader();

            _output.WriteLine(sb.ToString());
        }
    }
}
