//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace egregore {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("egregore.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm password: .
        /// </summary>
        internal static string ConfirmPasswordPrompt {
            get {
                return ResourceManager.GetString("ConfirmPasswordPrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to done.
        /// </summary>
        internal static string DecryptionCompleteMessage {
            get {
                return ResourceManager.GetString("DecryptionCompleteMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deriving a key from the password and decrypting the secret key....
        /// </summary>
        internal static string DecryptionInProgressMessage {
            get {
                return ResourceManager.GetString("DecryptionInProgressMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to done.
        /// </summary>
        internal static string EncryptionCompleteMessage {
            get {
                return ResourceManager.GetString("EncryptionCompleteMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deriving a key from the password in order to encrypt the secret key....
        /// </summary>
        internal static string EncryptionInProgressMessage {
            get {
                return ResourceManager.GetString("EncryptionInProgressMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter a password to protect the secret key..
        /// </summary>
        internal static string GenerateKeyInstructions {
            get {
                return ResourceManager.GetString("GenerateKeyInstructions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid characters in path.
        /// </summary>
        internal static string InvalidCharactersInPath {
            get {
                return ResourceManager.GetString("InvalidCharactersInPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid checksum function.
        /// </summary>
        internal static string InvalidChecksumFunction {
            get {
                return ResourceManager.GetString("InvalidChecksumFunction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wrong password for that key.
        /// </summary>
        internal static string InvalidDecryptionPassword {
            get {
                return ResourceManager.GetString("InvalidDecryptionPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid key capture.
        /// </summary>
        internal static string InvalidKeyCapture {
            get {
                return ResourceManager.GetString("InvalidKeyCapture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid key derivation function.
        /// </summary>
        internal static string InvalidKeyDerivationFunction {
            get {
                return ResourceManager.GetString("InvalidKeyDerivationFunction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid file buffer.
        /// </summary>
        internal static string InvalidKeyFileBuffer {
            get {
                return ResourceManager.GetString("InvalidKeyFileBuffer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid key file checksum.
        /// </summary>
        internal static string InvalidKeyFileChecksum {
            get {
                return ResourceManager.GetString("InvalidKeyFileChecksum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid key file key number.
        /// </summary>
        internal static string InvalidKeyFileKeyNumber {
            get {
                return ResourceManager.GetString("InvalidKeyFileKeyNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid key file path.
        /// </summary>
        internal static string InvalidKeyFilePath {
            get {
                return ResourceManager.GetString("InvalidKeyFilePath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid password length.
        /// </summary>
        internal static string InvalidPasswordLength {
            get {
                return ResourceManager.GetString("InvalidPasswordLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid signature algorithm.
        /// </summary>
        internal static string InvalidSignatureAlgorithm {
            get {
                return ResourceManager.GetString("InvalidSignatureAlgorithm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WARNING: Key file already exists, continuing will overwrite it.
        /// </summary>
        internal static string KeyFileAlreadyExists {
            get {
                return ResourceManager.GetString("KeyFileAlreadyExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to generate key file.
        /// </summary>
        internal static string KeyFileGenerateFailure {
            get {
                return ResourceManager.GetString("KeyFileGenerateFailure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Key file is an incorrect size.
        /// </summary>
        internal static string KeyFileInvalidSize {
            get {
                return ResourceManager.GetString("KeyFileInvalidSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Key file is missing.
        /// </summary>
        internal static string KeyFileIsMissing {
            get {
                return ResourceManager.GetString("KeyFileIsMissing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to read key file.
        /// </summary>
        internal static string KeyFileLoadFailure {
            get {
                return ResourceManager.GetString("KeyFileLoadFailure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Generated key file..
        /// </summary>
        internal static string KeyFileSuccess {
            get {
                return ResourceManager.GetString("KeyFileSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter the password to unlock the secret key..
        /// </summary>
        internal static string LoadKeyInstructions {
            get {
                return ResourceManager.GetString("LoadKeyInstructions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to capture password.
        /// </summary>
        internal static string PasswordFailure {
            get {
                return ResourceManager.GetString("PasswordFailure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to *.
        /// </summary>
        internal static string PasswordMask {
            get {
                return ResourceManager.GetString("PasswordMask", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Passwords don&apos;t match.
        /// </summary>
        internal static string PasswordMismatch {
            get {
                return ResourceManager.GetString("PasswordMismatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password: .
        /// </summary>
        internal static string PasswordPrompt {
            get {
                return ResourceManager.GetString("PasswordPrompt", resourceCulture);
            }
        }
    }
}
